"""initial

Revision ID: 252cfbb54a5a
Revises: 
Create Date: 2026-03-11 22:42:41.792231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252cfbb54a5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trending_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False, server_default='Untitled'))
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=2048), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('affiliate_links', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('analytics_json', sa.JSON(), nullable=True))
        batch_op.alter_column('growth_metric',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_trending_products_product_name'))
        batch_op.create_index(batch_op.f('ix_trending_products_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_trending_products_title'), ['title'], unique=False)
        batch_op.drop_column('product_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('trending_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_trending_products_title'))
        batch_op.drop_index(batch_op.f('ix_trending_products_brand'))
        batch_op.create_index(batch_op.f('ix_trending_products_product_name'), ['product_name'], unique=False)
        batch_op.alter_column('growth_metric',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('analytics_json')
        batch_op.drop_column('affiliate_links')
        batch_op.drop_column('price')
        batch_op.drop_column('description')
        batch_op.drop_column('brand')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
